image_tag := "naginata/core"

_default:
  @just --list

# Build the container image.
build *args:
  docker build -t {{image_tag}} {{args}} --build-arg build_platform={{arch()}} .

# Execute a container from the built image.
run *args:
  docker run --rm {{args}} -it {{image_tag}}

# Clean-up all unused images and data.
mrproper:
  docker image prune -af
  docker system prune -af --volumes
